/*
 * Tetris
 *
 * Originally generated by GitHub Copilot, cleaned up with Claude Code.
 *
 * The game runs in the wide screen mode (40x25 cells). The source is split into:
 * - game.c  - pieces, rules and scoring (no drawing)
 * - draw.c  - rendering
 * - input.c - keyboard handling
 * - tetris.c - main loop
 */

#ifndef TETRIS_H
#define TETRIS_H

#include "types.h"

// Board geometry (in screen cells)
#define BOARD_WIDTH         12
#define BOARD_HEIGHT        18
#define BOARD_LEFT          4              // screen column of the left border
#define BOARD_TOP           0              // screen row of the top border
#define PANEL_LEFT          (BOARD_LEFT + BOARD_WIDTH + 6)   // score, level, next piece
#define STATUS_TOP          (BOARD_TOP + BOARD_HEIGHT + 2)   // messages below the board

// Timing
#define POLL_MS             50             // keyboard polling interval
#define FALL_INITIAL_MS     400            // time between the piece's moves down
#define FALL_MIN_MS         100
#define FALL_SPEEDUP_MS     30             // per level
#define LINES_PER_LEVEL     10

// Screen codes of the glyphs used by the game. Codes from 128 up are free
// (ASCII text keeps rendering as text).
enum {
    SC_BLOCK = 128,
    SC_CORNER_TL, SC_CORNER_TR, SC_CORNER_BL, SC_CORNER_BR, SC_HLINE, SC_VLINE
};

typedef enum { PLAYING, PAUSED, GAME_OVER } State;

typedef enum { I_PIECE, O_PIECE, T_PIECE, S_PIECE, Z_PIECE, J_PIECE, L_PIECE } PieceType;
#define PIECE_TYPES 7

typedef u8 Rotation;                       // 0-3: 0, 90, 180, 270 degrees

typedef struct {
    i32 x;
    i32 y;
} Position;

typedef struct {
    PieceType type;
    Rotation rotation;
    Position pos;                          // board coordinates of the piece's 4x4 box
} Piece;

typedef struct {
    bool board[BOARD_HEIGHT][BOARD_WIDTH]; // settled blocks
    Piece current;
    PieceType next;
    u32 score;
    u32 level;
    u32 lines;
    u32 fall_ms;                           // current time between moves down
    u32 since_fall;                        // time since the last move down
    State state;
    bool quit;
} Game;

// game.c
void game_init(Game* game);
bool piece_cell(PieceType type, Rotation rotation, i32 x, i32 y);
bool game_fits(const Game* game, Position pos, Rotation rotation);
bool game_try_move(Game* game, i32 dx, i32 dy);
bool game_try_rotate(Game* game);
void game_fall(Game* game);
void game_drop(Game* game);
void game_toggle_pause(Game* game);

// draw.c
void draw_init(void);
void draw_frame(void);
void draw_game(const Game* game);

// input.c
void handle_input(Game* game);

#endif // TETRIS_H
