/*
 * Tetris
 *
 * Originally generated by GitHub Copilot, cleaned up with Claude Code.
 *
 * Controls:
 * - 'a', 'd' - move the piece left / right
 * - 'w' - rotate
 * - 's' - move the piece down (soft drop)
 * - space - drop the piece (hard drop)
 * - 'p' - pause / resume
 * - 'q' - quit
 * - 'r' - restart (when the game is over)
 */

#include "tetris.h"
#include "screen.h"
#include "sys_utils.h"
#include "terminal.h"

static Game game;

int main(void) {
    Game* g = &game;

    term_set_mode(1);
    term_hide_cursor();
    draw_init();

    game_init(g);
    draw_frame();

    while (!g->quit) {
        handle_input(g);

        if (g->state == PLAYING) {
            g->since_fall += POLL_MS;
            if (g->since_fall >= g->fall_ms) {
                game_fall(g);
            }
        }

        draw_game(g);
        sleep(POLL_MS);
    }

    clear_screen();
    term_reset();
    term_show_cursor();
    return 0;
}
