/*
 * Snake
 *
 * Originally generated by GitHub Copilot, cleaned up with Claude Code.
 *
 * The game runs in the wide screen mode (40x25 cells), with the snake,
 * the food and the board border rendered with Unicode glyphs.
 *
 * Controls:
 * - 'w', 'a', 's', 'd' - move up, left, down, right
 * - 'p' - pause / resume
 * - 'q' - quit
 * - 'r' - restart (when the game is over)
 */

#include "types.h"
#include "io.h"
#include "screen.h"
#include "string.h"
#include "sys_utils.h"
#include "terminal.h"
#include "time.h"

// Board geometry (in screen cells). The board itself is surrounded by a border.
#define BOARD_WIDTH     32
#define BOARD_HEIGHT    20
#define BOARD_LEFT      4                  // screen column of the left border
#define BOARD_TOP       1                  // screen row of the top border

#define MAX_LENGTH      (BOARD_WIDTH * BOARD_HEIGHT)
#define INITIAL_LENGTH  4
#define POINTS_PER_FOOD 10

#define MOVE_MS         200                // time between the snake's moves
#define POLL_MS         50                 // keyboard polling interval

// Screen codes of the glyphs used by the game. Codes from 128 up are free
// (ASCII text keeps rendering as text).
enum {
    SC_HEAD = 128, SC_BODY, SC_FOOD,
    SC_CORNER_TL, SC_CORNER_TR, SC_CORNER_BL, SC_CORNER_BR, SC_HLINE, SC_VLINE
};

static const struct { u8 code; u32 unicode; } GLYPHS[] = {
    { SC_HEAD,      0x26AA },              // medium white circle
    { SC_BODY,      0x25CF },              // black circle
    { SC_FOOD,      0x1F34E },             // red apple
    { SC_CORNER_TL, 0x256D },              // box drawing, rounded corners
    { SC_CORNER_TR, 0x256E },
    { SC_CORNER_BL, 0x2570 },
    { SC_CORNER_BR, 0x256F },
    { SC_HLINE,     0x2501 },              // heavy horizontal line
    { SC_VLINE,     0x2502 },              // light vertical line
};

typedef enum { UP, RIGHT, DOWN, LEFT } Direction;

typedef enum { PLAYING, PAUSED, GAME_OVER } State;

// Board coordinates: 0 <= x < BOARD_WIDTH, 0 <= y < BOARD_HEIGHT
typedef struct {
    u8 x;
    u8 y;
} Point;

typedef struct {
    Point segments[MAX_LENGTH];            // segments[0] is the head
    u32 length;
    Direction direction;                   // direction of the last move
    Direction next_direction;              // direction of the next move (from keyboard)
    Point food;
    u32 score;
    State state;
    bool quit;
} Game;

static Game game;                          // too big for the stack


//----------------------------------------------------------------------------
// Random numbers (there is no RNG in the OS yet)

static u32 rng_state;

static void rng_init(void) {
    Result now = time_now();
    rng_state = now.err ? 0x2545F491 : now.val;   // fixed seed without an RTC
}

// Returns a pseudo-random number from 0 to range-1
static u32 rng_next(u32 range) {
    rng_state = rng_state * 1103515245 + 12345;
    return (rng_state >> 16) % range;
}


//----------------------------------------------------------------------------
// Drawing

static void draw_at(u32 col, u32 row, const char* str) {
    set_cursor_pos(col, row);
    prints(str);
}

// printc() takes a char, while the glyph codes are above 127
static void put(u8 code) {
    printc((char) code);
}

static void draw_cell(Point p, u8 code) {
    set_cursor_pos(BOARD_LEFT + 1 + p.x, BOARD_TOP + 1 + p.y);
    put(code);
}

static void draw_stats(const Game* g) {
    set_cursor_pos(BOARD_LEFT, 0);
    prints("Score: ");
    printnum(g->score);
    set_cursor_pos(BOARD_LEFT + BOARD_WIDTH - 9, 0);
    prints("Length: ");
    printnum(g->length);
}

static void draw_horizontal_border(u32 row, u8 left_corner, u8 right_corner) {
    set_cursor_pos(BOARD_LEFT, row);
    put(left_corner);
    for (u32 x = 0; x < BOARD_WIDTH; x++) put(SC_HLINE);
    put(right_corner);
}

static void draw_border(void) {
    draw_horizontal_border(BOARD_TOP, SC_CORNER_TL, SC_CORNER_TR);
    for (u32 y = 0; y < BOARD_HEIGHT; y++) {
        set_cursor_pos(BOARD_LEFT, BOARD_TOP + 1 + y);
        put(SC_VLINE);
        set_cursor_pos(BOARD_LEFT + BOARD_WIDTH + 1, BOARD_TOP + 1 + y);
        put(SC_VLINE);
    }
    draw_horizontal_border(BOARD_TOP + BOARD_HEIGHT + 1, SC_CORNER_BL, SC_CORNER_BR);
}

// Draws everything: used when the game (re)starts and after a pause,
// otherwise the screen is updated incrementally, cell by cell
static void draw_all(const Game* g) {
    clear_screen();
    draw_stats(g);
    draw_border();
    draw_cell(g->food, SC_FOOD);
    for (u32 i = g->length; i-- > 0; ) {
        draw_cell(g->segments[i], i == 0 ? SC_HEAD : SC_BODY);
    }
}

// Draws a line of text centered on the board
static void draw_centered(u32 row, const char* str) {
    draw_at(BOARD_LEFT + 1 + (BOARD_WIDTH - strlen(str)) / 2, row, str);
}

// Draws a message in the middle of the board
static void draw_message(const char* line1, const char* line2, const char* line3) {
    const u32 row = BOARD_TOP + BOARD_HEIGHT / 2;
    draw_centered(row, line1);
    if (line2) draw_centered(row + 2, line2);
    if (line3) draw_centered(row + 3, line3);
}


//----------------------------------------------------------------------------
// Game logic

static bool is_snake(const Game* g, Point p, u32 from, u32 to) {
    for (u32 i = from; i < to; i++) {
        if (g->segments[i].x == p.x && g->segments[i].y == p.y) return true;
    }
    return false;
}

// Places the food on a random cell not occupied by the snake
static void spawn_food(Game* g) {
    do {
        g->food.x = rng_next(BOARD_WIDTH);
        g->food.y = rng_next(BOARD_HEIGHT);
    } while (is_snake(g, g->food, 0, g->length));
}

static void new_game(Game* g) {
    rng_init();
    g->length = INITIAL_LENGTH;
    g->direction = RIGHT;
    g->next_direction = RIGHT;
    g->score = 0;
    g->state = PLAYING;

    // The snake starts horizontally in the left half of the board, heading right
    for (u32 i = 0; i < g->length; i++) {
        g->segments[i].x = BOARD_WIDTH / 4 - i;
        g->segments[i].y = BOARD_HEIGHT / 2;
    }

    spawn_food(g);
    draw_all(g);
}

static void end_game(Game* g, const char* reason) {
    g->state = GAME_OVER;
    draw_message(reason, "Press 'r' to restart", "or 'q' to quit");
}

// Moves the snake by one cell
static void move(Game* g) {
    g->direction = g->next_direction;

    i32 x = g->segments[0].x;
    i32 y = g->segments[0].y;
    switch (g->direction) {
        case UP:    y--; break;
        case DOWN:  y++; break;
        case LEFT:  x--; break;
        case RIGHT: x++; break;
    }

    if (x < 0 || x >= BOARD_WIDTH || y < 0 || y >= BOARD_HEIGHT) {
        end_game(g, "GAME OVER!");
        return;
    }

    Point head = { x, y };
    bool eats = head.x == g->food.x && head.y == g->food.y;

    // The tail moves away this turn (unless the snake grows), so it doesn't count
    u32 body_end = eats ? g->length : g->length - 1;
    if (is_snake(g, head, 1, body_end)) {
        end_game(g, "GAME OVER!");
        return;
    }

    // Every segment takes the place of its predecessor. When the snake
    // grows, the old tail stays where it is and becomes the new last segment.
    Point tail = g->segments[g->length - 1];
    if (eats) g->length++;
    for (u32 i = g->length - 1; i > 0; i--) {
        g->segments[i] = g->segments[i - 1];
    }
    g->segments[0] = head;

    draw_cell(g->segments[1], SC_BODY);
    draw_cell(head, SC_HEAD);

    if (eats) {
        g->score += POINTS_PER_FOOD;
        draw_stats(g);
        if (g->length == MAX_LENGTH) {
            end_game(g, "YOU WON!");
            return;
        }
        spawn_food(g);
        draw_cell(g->food, SC_FOOD);
    } else {
        draw_cell(tail, ' ');
    }
}

static void turn(Game* g, Direction dir) {
    // Ignore a U-turn, it would mean an instant collision with the neck
    bool reverse = (dir == UP && g->direction == DOWN) || (dir == DOWN && g->direction == UP)
                || (dir == LEFT && g->direction == RIGHT) || (dir == RIGHT && g->direction == LEFT);
    if (!reverse) g->next_direction = dir;
}

static void toggle_pause(Game* g) {
    if (g->state == PLAYING) {
        g->state = PAUSED;
        draw_message("PAUSED", 0, 0);
    } else if (g->state == PAUSED) {
        g->state = PLAYING;
        draw_all(g);
    }
}

// Processes all the keys pressed since the last call
static void handle_input(Game* g) {
    i32 key;
    while ((key = getc()) >= 0) {
        switch (key) {
            case 'w': case 'W': turn(g, UP); break;
            case 's': case 'S': turn(g, DOWN); break;
            case 'a': case 'A': turn(g, LEFT); break;
            case 'd': case 'D': turn(g, RIGHT); break;
            case 'p': case 'P': toggle_pause(g); break;
            case 'r': case 'R': if (g->state == GAME_OVER) new_game(g); break;
            case 'q': case 'Q': g->quit = true; break;
        }
    }
}


//----------------------------------------------------------------------------

int main(void) {
    Game* g = &game;

    term_set_mode(1);
    term_hide_cursor();
    for (u32 i = 0; i < sizeof(GLYPHS) / sizeof(GLYPHS[0]); i++) {
        term_set_screencode(GLYPHS[i].code, GLYPHS[i].unicode);
    }

    new_game(g);

    u32 since_move = 0;
    while (!g->quit) {
        handle_input(g);
        if (g->state == PLAYING) {
            since_move += POLL_MS;
            if (since_move >= MOVE_MS) {
                since_move = 0;
                move(g);
            }
        }
        sleep(POLL_MS);
    }

    clear_screen();
    term_reset();
    term_show_cursor();
    return 0;
}
